### ISSUE TITLE
onActivityResult need super in release-0.1.0-alpha

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native-fbsdk#111]
We need to have super to avoid [this problem](https://github.com/marcshilling/react-native-image-picker/issues/164) when implementing other package makes use of onActivityResult event
```
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    //other package won't work if don't have next line
    super.onActivityResult(requestCode, resultCode, data); 
    mCallbackManager.onActivityResult(requestCode, resultCode, data);
}
```

**Comment by bcalik** [comment]
Wow, I have just came here to report the same issue. Wasted hours to debug.

But adding super does not solve my issue, it leads to another error.

Here is the full error output. Somehow it triggers `com.facebook.reactnative.androidsdk.FBSDKDialogBaseJavaModule.onActivityResult(FBSDKDialogBaseJavaModule.java:46)`
```
04-10 16:17:46.898 10030-10030/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.myapp, PID: 10030
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { act=com.htc.HTCAlbum.action.ITEM_PICKER_FROM_COLLECTIONS (has extras) }} to activity {com.myapp/com.myapp.MainActivity}: java.lang.NullPointerException
     at android.app.ActivityThread.deliverResults(ActivityThread.java:3942)
     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3992)
     at android.app.ActivityThread.access$1300(ActivityThread.java:156)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:157)
     at android.app.ActivityThread.main(ActivityThread.java:5872)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
     at dalvik.system.NativeStart.main(Native Method)
  Caused by: java.lang.NullPointerException
     at com.facebook.reactnative.androidsdk.FBSDKDialogBaseJavaModule.onActivityResult(FBSDKDialogBaseJavaModule.java:46)
     at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:189)
     at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:597)
     at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:180)
     at com.myapp.MainActivity.onActivityResult(MainActivity.java:48)
     at android.app.Activity.dispatchActivityResult(Activity.java:5535)
     at android.app.ActivityThread.deliverResults(ActivityThread.java:3938)
     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3992) 
     at android.app.ActivityThread.access$1300(ActivityThread.java:156) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:157) 
     at android.app.ActivityThread.main(ActivityThread.java:5872) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by chrisp-fb** [comment]
Thanks for the detailed report and code snippet. 

As noted in the README, you need to add `mCallbackManager = new CallbackManager.Factory().create();` at the beginning of your `getPackages()`. The NPE you're seeing is because mCallbackManager was not initialized.

Feel free to reopen if that doesn't fix your issue.
