### ISSUE TITLE
onResume causing exception on start in release-0.1.0-alpha

### ISSUE THREAD

**Issue by ericraio** [facebook/react-native-fbsdk#112]
The app will crash when starting. I was getting this exception when I added onResume to my MainActivity.java

```
E/AndroidRuntime( 3466): java.lang.RuntimeException: Unable to resume activity {APP_NAME.MainActivity}: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2774)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 3466): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3466): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 3466): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3466): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3466): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 3466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 3466): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3466): Caused by: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
E/AndroidRuntime( 3466): 	at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:281)
E/AndroidRuntime( 3466): 	at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:268)
E/AndroidRuntime( 3466): 	at com.appname.MainActivity.onResume(MainActivity.java:79)
E/AndroidRuntime( 3466): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/AndroidRuntime( 3466): 	at android.app.Activity.performResume(Activity.java:5310)
E/AndroidRuntime( 3466): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
E/AndroidRuntime( 3466): 	... 12 more
```

**Comment by dzhuowen** [comment]
Hi, can you provide the app's MainActivity.java here?

**Comment by ericraio** [comment]
@dzhuowen 

```
package com.appName;

import android.content.Intent;     // <--- import
import com.facebook.appevents.AppEventsLogger; 
import android.os.Bundle;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.audioManager.AudioManager;
import com.rnfs.RNFSPackage;
import com.facebook.react.ReactActivity;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.brentvatne.react.ReactVideoPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.AirMaps.AirPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {
    CallbackManager mCallbackManager;

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "AppName";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
      mCallbackManager = new CallbackManager.Factory().create();
      ReactPackage packages[] = new ReactPackage[]{
        new MainReactPackage(),
        new VectorIconsPackage(),
        new ReactVideoPackage(),
        new AudioManager(),
        new RNFSPackage(),
        new LinearGradientPackage(),
        new AirPackage(),
      };
      return Arrays.<ReactPackage>asList(packages);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      FacebookSdk.sdkInitialize(getApplicationContext());
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
      super.onActivityResult(requestCode, resultCode, data);
      mCallbackManager.onActivityResult(requestCode, resultCode, data);
    }

  @Override
  protected void onResume() {
      super.onResume();
      AppEventsLogger.activateApp(getApplicationContext());
  }

  @Override
  protected void onPause() {
      super.onPause();
      AppEventsLogger.deactivateApp(getApplicationContext());
  }

  @Override
  protected void onStop() {
      super.onStop();
      AppEventsLogger.onContextStop();
  }

}
```

**Comment by ericraio** [comment]
This was a setup configuration issue, I got everything working.
