### ISSUE TITLE
Error npm install react-native-fbsdk 

### ISSUE THREAD

**Issue by jerson** [facebook/react-native-fbsdk#124]
1) create new project
```
➜   react-native init fbprueba
```
2) install sdk
```
➜  npm install --save react-native-fbsdk


> bufferutil@1.2.1 install /Users/gerson/Desktop/fbprueba/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-04-19 09:33:38.289 xcodebuild[10946:61503] Build settings from command line:
2016-04-19 09:33:38.290 xcodebuild[10946:61503]     ENABLE_BITCODE = NO
2016-04-19 09:33:38.290 xcodebuild[10946:61503]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-04-19 09:33:38.290 xcodebuild[10946:61503]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-04-19 09:33:38.290 xcodebuild[10946:61503]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-04-19 09:33:38.290 xcodebuild[10946:61503]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gerson/Desktop/fbprueba/node_modules/bufferutil
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install /Users/gerson/Desktop/fbprueba/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-04-19 09:33:40.048 xcodebuild[11039:61645] Build settings from command line:
2016-04-19 09:33:40.049 xcodebuild[11039:61645]     ENABLE_BITCODE = NO
2016-04-19 09:33:40.049 xcodebuild[11039:61645]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-04-19 09:33:40.049 xcodebuild[11039:61645]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-04-19 09:33:40.049 xcodebuild[11039:61645]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-04-19 09:33:40.049 xcodebuild[11039:61645]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gerson/Desktop/fbprueba/node_modules/utf-8-validate
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
```

3) try install sdk with nvm 
```
➜ npm install --save react-native-fbsdk
> bufferutil@1.2.1 install /Users/gerson/Desktop/fbprueba/node_modules/bufferutil
> node-gyp rebuild

2016-04-19 09:38:10.412 xcodebuild[15940:68884] Build settings from command line:
2016-04-19 09:38:10.412 xcodebuild[15940:68884]     ENABLE_BITCODE = NO
2016-04-19 09:38:10.412 xcodebuild[15940:68884]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-04-19 09:38:10.413 xcodebuild[15940:68884]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-04-19 09:38:10.413 xcodebuild[15940:68884]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-04-19 09:38:10.413 xcodebuild[15940:68884]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gerson/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/gerson/.nvm/versions/node/v5.3.0/bin/node" "/Users/gerson/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gerson/Desktop/fbprueba/node_modules/bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install /Users/gerson/Desktop/fbprueba/node_modules/utf-8-validate
> node-gyp rebuild

2016-04-19 09:38:12.666 xcodebuild[16033:69054] Build settings from command line:
2016-04-19 09:38:12.667 xcodebuild[16033:69054]     ENABLE_BITCODE = NO
2016-04-19 09:38:12.667 xcodebuild[16033:69054]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-04-19 09:38:12.667 xcodebuild[16033:69054]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-04-19 09:38:12.667 xcodebuild[16033:69054]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-04-19 09:38:12.667 xcodebuild[16033:69054]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gerson/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/gerson/.nvm/versions/node/v5.3.0/bin/node" "/Users/gerson/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gerson/Desktop/fbprueba/node_modules/utf-8-validate
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
fbprueba@0.0.1 /Users/gerson/Desktop/fbprueba
└── react-native-fbsdk@0.1.0 
```

**Comment by dzhuowen** [comment]
Not really sure about the reason :-( but I will suggest updating your dev environment.

**Comment by jerson** [comment]
The problem was with bufferutil and nodejs 5 

ref: https://github.com/websockets/bufferutil/issues/36
