### ISSUE TITLE
Events not received in dashboard

### ISSUE THREAD

**Issue by cjmarkham** [facebook/react-native-fbsdk#135]
I have installed and configured the SDK as explained in the readme. I have a custom event set up and can see in my terminal that the event is triggered. Yet, when I view the Event Debugging section in the Analytics dashboard, I can only see the App Installs events, not the custom one I am using.

Code to send the event:
```
const FBSDK = require('react-native-fbsdk');
const {
  AppEventsLogger,
} = FBSDK;

// ...

AppEventsLogger.logEvent('some_eventy');
```

Console response

```
FacebookSDK.AppEvents: Created app event '{"_eventName":"some_eventy","_logTime":1461427107,"_ui":"ReactApplicationContext","_valueToSum":0}'
```

The following logs from `adb logcat` may be useful

```
com.facebook.appevents.AppEventsLogger: To set source application the context of activateApp must be an instance of Activity
```

```
04-23 14:18:14.126 14429 14429 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.hundredrooms/com.hundredrooms.MainActivity}: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3158)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3189)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2527)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5514)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:346)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:325)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at com.hundredrooms.MainActivity.onResume(MainActivity.java:85)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6346)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3147)
04-23 14:18:14.126 14429 14429 E AndroidRuntime: 	... 10 more
```

**Comment by chrisp-fb** [comment]
Does `AppEventsLogger.flush()` help? It may be that the app events just haven't been flushed yet when you were looking.

**Comment by dzhuowen** [comment]
Closing the issue b/c of inactivity. Feel free to reopen if the problem doesn't get resolved.

**Comment by n-sviridenko** [comment]
Still the issue. @chrisp-fb flush doesn't help. It works only on iOS. KeyHash is valid. There is no console events neither from `AppEventsLogger` nor from `AppEvents` at all. We use expo.

**Comment by n-sviridenko** [comment]
Our integration:
```diff
diff --git a/customer/android/app/build.gradle b/customer/android/app/build.gradle
index 12a9f571..c2da0d40 100644
--- a/customer/android/app/build.gradle
+++ b/customer/android/app/build.gradle
@@ -181,6 +181,9 @@ dependencies {
   api project(':expo-firebase-analytics')
   api project(':expo-firebase-app')
 
+  implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
+  implementation project(':react-native-fbsdk')
+
   /* REMOVED_WHEN_DISTRIBUTING_FROM_HERE
   implementation(project(path: ':expoview')) {
     // Excluding okhttp3 included by expo-file-system
diff --git a/customer/android/app/src/main/AndroidManifest.xml b/customer/android/app/src/main/AndroidManifest.xml
index 464f8a0a..84f362cf 100644
--- a/customer/android/app/src/main/AndroidManifest.xml
+++ b/customer/android/app/src/main/AndroidManifest.xml
@@ -314,7 +314,7 @@
     <!-- ADD BRANCH CONFIG HERE -->
 
     <!-- The Facebook SDK runs FacebookInitProvider on startup and crashes if there isn't an ID here -->
-    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="fb0"/>
+    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
 
     <meta-data android:name="standaloneStripeScheme" android:value="xxx" />
   </application>
diff --git a/customer/android/app/src/main/java/host/exp/exponent/MainActivity.java b/customer/android/app/src/main/java/host/exp/exponent/MainActivity.java
index 5680a729..365766f9 100644
--- a/customer/android/app/src/main/java/host/exp/exponent/MainActivity.java
+++ b/customer/android/app/src/main/java/host/exp/exponent/MainActivity.java
@@ -1,6 +1,7 @@
 package host.exp.exponent;
 
 import android.os.Bundle;
+import android.content.Intent;
 
 import com.facebook.react.ReactPackage;
 
@@ -58,4 +59,10 @@ public class MainActivity extends DetachActivity {
     // Add extra initialProps here
     return expBundle;
   }
+
+  @Override
+  public void onActivityResult(int requestCode, int resultCode, Intent data) {
+    super.onActivityResult(requestCode, resultCode, data);
+    MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
+  }
 }
diff --git a/customer/android/app/src/main/java/host/exp/exponent/MainApplication.java b/customer/android/app/src/main/java/host/exp/exponent/MainApplication.java
index 2538c18e..a6bce000 100644
--- a/customer/android/app/src/main/java/host/exp/exponent/MainApplication.java
+++ b/customer/android/app/src/main/java/host/exp/exponent/MainApplication.java
@@ -2,6 +2,9 @@ package host.exp.exponent;
 
 
 import com.facebook.react.ReactPackage;
+import com.facebook.CallbackManager;
+import com.facebook.reactnative.androidsdk.FBSDKPackage;
+import com.facebook.appevents.AppEventsLogger;
 
 import java.util.Arrays;
 import java.util.List;
@@ -10,9 +13,22 @@ import expolib_v1.okhttp3.OkHttpClient;
 
 // Needed for `react-native link`
 // import com.facebook.react.ReactApplication;
+import com.facebook.reactnative.androidsdk.FBSDKPackage;
 
 public class MainApplication extends ExpoApplication {
 
+  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();
+
+  protected static CallbackManager getCallbackManager() {
+    return mCallbackManager;
+  }
+
+  @Override
+  public void onCreate() {
+    super.onCreate();
+    AppEventsLogger.activateApp(this);
+  }
+
   @Override
   public boolean isDebug() {
     return BuildConfig.DEBUG;
@@ -25,7 +41,8 @@ public class MainApplication extends ExpoApplication {
         // TODO: add native modules!
 
         // Needed for `react-native link`
-        // new MainReactPackage()
+        // new MainReactPackage(),
+        new FBSDKPackage(mCallbackManager)
     );
   }
 
diff --git a/customer/android/app/src/main/res/values/strings.xml b/customer/android/app/src/main/res/values/strings.xml
index 73cde6d4..0057724a 100644
--- a/customer/android/app/src/main/res/values/strings.xml
+++ b/customer/android/app/src/main/res/values/strings.xml
@@ -1,5 +1,7 @@
 <resources>
   <string name="app_name">Our app</string>
+  <string name="facebook_app_id">xxxx</string>
+  <string name="fb_login_protocol_scheme">fbxxxx</string>
   <string name="dev_activity_name">Exponent Dev</string>
   <string name="preference_file_key">host.exp.exponent.SharedPreferences</string>
   <string name="error_header">Something went wrong.</string>
diff --git a/customer/android/settings.gradle b/customer/android/settings.gradle
index 8d8730a0..8bc19aca 100644
--- a/customer/android/settings.gradle
+++ b/customer/android/settings.gradle
@@ -1,5 +1,8 @@
 include ':app'
 
+include ':react-native-fbsdk'
+project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')
+
 include ':expo-core'
 project(':expo-core').projectDir = new File(rootProject.projectDir, '../node_modules/expo-core/android')
```
