### ISSUE TITLE
Newest Facebook SDK (4.13) causes Android crash

### ISSUE THREAD

**Issue by cmcewen** [facebook/react-native-fbsdk#219]
Pinning the version to 4.12.1 solves this problem

```
E/AndroidRuntime( 6969): java.lang.NullPointerException: Argument 'context' cannot be null
E/AndroidRuntime( 6969):     at com.facebook.internal.Validate.notNull(Validate.java:76)
E/AndroidRuntime( 6969):     at com.facebook.internal.Utility.getMetadataApplicationId(Utility.java:594)
E/AndroidRuntime( 6969):     at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:757)
E/AndroidRuntime( 6969):     at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:732)
E/AndroidRuntime( 6969):     at com.facebook.appevents.AppEventsLogger.newLogger(AppEventsLogger.java:400)
E/AndroidRuntime( 6969):     at com.facebook.reactnative.androidsdk.FBAppEventsLoggerModule.initialize(FBAppEventsLoggerModule.java:117)
E/AndroidRuntime( 6969):     at com.facebook.react.bridge.NativeModuleRegistry.notifyCatalystInstanceInitialized(NativeModuleRegistry.java:114)
E/AndroidRuntime( 6969):     at com.facebook.react.bridge.CatalystInstanceImpl.initialize(CatalystInstanceImpl.java:275)
E/AndroidRuntime( 6969):     at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:727)
E/AndroidRuntime( 6969):     at com.facebook.react.ReactInstanceManagerImpl.access$800(ReactInstanceManagerImpl.java:102)
E/AndroidRuntime( 6969):     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:208)
E/AndroidRuntime( 6969):     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:181)
E/AndroidRuntime( 6969):     at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 6969):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 6969):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 6969):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6969):     at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6969):     at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 6969):     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6969):     at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6969):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 6969):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 6969):     at dalvik.system.NativeStart.main(Native Method)```

**Comment by leledumbo549** [comment]
same error here. how you pin fb-sdk version to 4.12.1?

**Comment by luisfuertes** [comment]
Same here

**Comment by pelayo** [comment]
+1

**Comment by anton6** [comment]
@pelayo Thanks for that

**Comment by charpeni** [comment]
cc @dzhuowen

**Comment by dzhuowen** [comment]
Thanks for the notification! Please roll back to 4.12 for now. We'll roll out a fix for Android SDK soon.
Keeping the issue open till the Android SDK fix is up.

**Comment by cmcewen** [comment]
Can you update the `build.gradle` file and push a fix to npm?

**Comment by adeelraza** [comment]
+1

**Comment by duranmla** [comment]
+1

**Comment by dzhuowen** [comment]
Just ship the android-sdk-4.13.1.  It should be updated on Maven soon.

**Comment by dzhuowen** [comment]
Android-sdk 4.13.1 is up on Maven. Please do a gradle build to pull the latest sdk.

**Comment by charpeni** [comment]
Thank you for this fast hotfix @dzhuowen
