### ISSUE TITLE
evaluating '_reactNativeFacebookLogin.FBLoginManager.loginWithPermissions from Android signed APK

### ISSUE THREAD

**Issue by viktor-schneider** [facebook/react-native-fbsdk#251]
Hi!

Im trying to implement a facebook-Login by using the LoginManager that the react-native-fbsdk provides.

Now the problem is, that I get the following error when trying to log in with facebook with a signed APK:

```
 undefined is not a function (evaluating '_reactNativeFacebookLogin.FBLoginManager.loginWithPermissions')
 Unable to symbolicate stack trace: Bundle was not loaded from the packager
 FATAL EXCEPTION: mqt_native_modules
 Process: com.solopro.dogwood, PID: 8208
 com.facebook.react.modules.core.JavascriptException: undefined is not a function (evaluating '_reactNativeFacebookLogin.FBLoginManager.loginWithPermissio
 ns'), stack:
 facebookLogin@76454:62
 touchableHandlePress@52180:39
 _performSideEffectsForTransition@21343:26
 _receiveSignal@21259:38
 touchableHandleResponderRelease@21033:20
 invokeGuardedCallback@15044:12
 executeDispatch@14877:38
 executeDispatchesInOrder@14900:16
 executeDispatchesAndRelease@14354:42
 executeDispatchesAndReleaseTopLevel@14365:35
 forEachAccumulated@15179:12
 processEventQueue@14527:19
 runEventQueueInBatch@15204:33
 handleTopLevel@15215:21
 <unknown>@14147:39
 perform@16143:16
 batchedUpdates@31745:20
 batchedUpdates@15373:32
 _receiveRootNodeIDEvent@14146:28
 receiveTouches@14208:48
 __callFunction@7706:28
 <unknown>@7613:22
 guard@7564:3
 callFunctionReturnFlushedQueue@7612:6
     at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:90)
     at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
     at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
     at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
     at android.os.Looper.loop(Looper.java:135)
     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
     at java.lang.Thread.run(Thread.java:818)
```

I set up the module by following the instructions.

It seems to be weird, that the error points out the function `loginWithPermissions` that is not even available in the Android package but in iOS only.

My Login function looks something like this:
`LoginManager.logInWithReadPermissions(['public_profile', 'email']).then( ... )`

I already checked the facebook-id and the keyhash - everything seems to be fine.

**Comment by dzhuowen** [comment]
The error message indicates `FBLoginManager.loginWithPermissions` is not a valid JS API and this is true for rnsdk. It should either be logInWithReadPermissions or logInWithPublishPermissions.

**Comment by viktor-schneider** [comment]
Yes, the problem is that I don't use the `loginWithPermissions` function.

My facebook-login function looks like this:


```
facebookLogin() {
	var self = this;
	LoginManager.logInWithReadPermissions(['public_profile', 'email']).then(
		function (response) {
			const data = {token: response.credentials.token, provider: "facebook"};
			const register = ()=> {
				self.props.dispatch({type: ActionTypes.FETCH_DATA});
				Backend.users
					   .create(data)
					   .then((response)=> {
						   self.props.dispatch({type: ActionTypes.RECEIVE_DATA});
						   self.checkLogin(response);
					   })
					   .catch(error=> {
						   self.props.dispatch({type: ActionTypes.RECEIVE_DATA});
						   console.log(error);
					   });
			};
			const login = ()=> {
				self.props.dispatch({type: ActionTypes.FETCH_DATA});
				Backend.login
					   .create(data)
					   .then((response)=> {
						   self.props.dispatch({type: ActionTypes.RECEIVE_DATA});
						   self.checkLogin(response);
					   })
					   .catch(error=> {
						   self.props.dispatch({type: ActionTypes.RECEIVE_DATA});
						   if (error && error.status === 401) {
							   register();
						   }
					   });
			};
			login();
		}, function (error) {
			console.log("Error: ", response);
		});
}
```

**Comment by dzhuowen** [comment]
Hi @viktor-schneider, I don't see any problems with your code. Please file a bug on https://developers.facebook.com/bugs/. You can secure upload a sample app there so I can debug on that.

**Comment by dzhuowen** [comment]
Closing for inactivity.
