### ISSUE TITLE
Crash when using `publishPermissions` instead of `readPermissions` prop on `LoginButton`

### ISSUE THREAD

**Issue by EvNaverniouk** [facebook/react-native-fbsdk#260]
When using the following code:
```
<LoginButton publishPermissions={["public_profile", "user_friends"]} />
```

Clicking on the button will result in a full Android app crash:

```
08-06 16:24:16.870 4142-4142/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myapp, PID: 4142
Cannot pass a read permission (public_profile) to a request for publish authorization
at com.facebook.login.LoginManager.validatePublishPermissions(LoginManager.java:383)
at com.facebook.login.LoginManager.logInWithPublishPermissions(LoginManager.java:356)
at com.facebook.login.widget.LoginButton$LoginClickListener.performLogin(LoginButton.java:724)
at com.facebook.login.widget.LoginButton$LoginClickListener.onClick(LoginButton.java:701)
at com.facebook.FacebookButtonBase$1.onClick(FacebookButtonBase.java:385)
at android.view.View.performClick(View.java:4756)
at android.view.View$PerformClick.run(View.java:19749)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Of course the solution is to use `readPermissions` instead of `publishPermissions`. But I didn't expect that using a bad prop on the component would result in a full application crash.

Is there some way to catch these types of errors and report it as an "error" in the `onLoginFinished` instead? That would greatly improve the developer experience.

**Comment by chrisp-fb** [comment]
Hey @EvNaverniouk , thanks for the feedback - this is by design since we wanted to make sure developers are asking for permissions correctly and permissions should not change at runtime. If the exception message was unclear, do you have suggestions on changing it (feel free to submit a pull request to the [code in the Android SDK](https://github.com/facebook/facebook-android-sdk/blob/308adb492d1017a826008c63ac3eed5f0d4be84a/facebook/src/main/java/com/facebook/login/LoginManager.java#L385) )?
