### ISSUE TITLE
The module `./FBAppInviteDialog` could not be found

### ISSUE THREAD

**Issue by zomlaaa95** [facebook/react-native-fbsdk#564]
Got this error when switched to 0.10.0 version: (already did npm i and link, but it keeps breaking)

bundling failed: Error: Unable to resolve module `./FBAppInviteDialog` from `/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/react-native-fbsdk/js/index.js`: The module `./FBAppInviteDialog` could not be found from `/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/react-native-fbsdk/js/index.js`. Indeed, none of these files exist:
  * `/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/react-native-fbsdk/js/FBAppInviteDialog(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/react-native-fbsdk/js/FBAppInviteDialog/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:120:15)
    at ResolutionRequest.resolveDependency (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/home/lazar-he/projects/react-native/vinsent-react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)

**Comment by redcancode** [comment]
can you try running the packager by resetting the packager cache? `react-native start --reset-cache`

**Comment by zomlaaa95** [comment]
Thank you very much, that solved the problem :)
