### ISSUE TITLE
None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by codesoverflow** [facebook/react-native-fbsdk#789]
Followed all the steps but still, it is not working.
Please check the below error, I found in the console while creating debug build.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > No matching configuration of project :react-native-fbads was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.gradle.internal.dependency.AndroidTypeAttr' with value 'Aar' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-fbads.
     Required by:
         project :app
      > No matching configuration of project :react-native-fbads was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.gradle.internal.dependency.AndroidTypeAttr' with value 'Aar' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

    at makeError (/var/codes/react-native/appSize/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/codes/react-native/appSize/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appSize@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appSize@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jaswant/.npm/_logs/2020-08-15T13_33_48_636Z-debug.log

**Comment by mohammadmaleh** [comment]
having the same issue

**Comment by yasser17** [comment]
same issue

**Comment by salman660** [comment]
same issue here

**Comment by akhzarna** [comment]
having the same issue, can anyone help me ?

**Comment by tahirhameed** [comment]
Having the same issue ?

**Comment by haxonadora** [comment]
try changing the order of lines in `settings.gradle` to this:
```
applyNativeModulesSettingsGradle(settings)
include ':react-native-fbads'
project(':react-native-fbads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbads/android/app/')
include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')
```

`applyNativeModulesSettingsGradle(settings)` has to be before linking lines

**Comment by akhzarna** [comment]
I have already implemented admob, No need to go with facebook audience networks
